// <auto-generated />
using System;
using System.Collections.Generic;
using HermesDeck.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HermesDeck.Api.Persistence.Migrations
{
    [DbContext(typeof(HermesDeckDbContext))]
    [Migration("0001_InitialControlDeck")]
    partial class InitialControlDeck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HermesDeck.Api.Domain.AgentRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByIdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RunId");

                    b.HasIndex("ConversationId");

                    b.ToTable("AgentRuns");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.ApprovalDecision", b =>
                {
                    b.Property<string>("DecisionId")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("DecisionId");

                    b.HasIndex("ApprovalId")
                        .IsUnique();

                    b.HasIndex("IdentityId");

                    b.ToTable("ApprovalDecisions");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.ApprovalRequest", b =>
                {
                    b.Property<string>("ApprovalId")
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AffectedTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImpactSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.HasKey("ApprovalId");

                    b.HasIndex("RunId");

                    b.HasIndex("ToolCallId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Conversation", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastRunId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConversationId");

                    b.HasIndex("IdentityId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.HermesIdentity", b =>
                {
                    b.Property<string>("IdentityId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdentityId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("HermesIdentities");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Message", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.Property<int>("StreamState")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("IdentityId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Panel", b =>
                {
                    b.Property<string>("PanelId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("AllowedActions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RenderingMode")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PanelId");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.PanelIntent", b =>
                {
                    b.Property<string>("IntentId")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DenialReason")
                        .HasColumnType("text");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadSummary")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IntentId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("PanelId");

                    b.ToTable("PanelIntents");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LaunchSource")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.HasIndex("IdentityId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.TelegramUser", b =>
                {
                    b.Property<string>("TelegramUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("TelegramUserId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.TimelineEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<IReadOnlyDictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("RunId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.ToolCall", b =>
                {
                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ToolCallId");

                    b.HasIndex("RunId");

                    b.ToTable("ToolCalls");
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.AgentRun", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.ApprovalDecision", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.ApprovalRequest", null)
                        .WithOne()
                        .HasForeignKey("HermesDeck.Api.Domain.ApprovalDecision", "ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HermesDeck.Api.Domain.HermesIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.ApprovalRequest", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HermesDeck.Api.Domain.ToolCall", null)
                        .WithMany()
                        .HasForeignKey("ToolCallId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Conversation", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.HermesIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.HermesIdentity", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.TelegramUser", null)
                        .WithOne()
                        .HasForeignKey("HermesDeck.Api.Domain.HermesIdentity", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Message", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Notification", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.HermesIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.PanelIntent", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.HermesIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HermesDeck.Api.Domain.Panel", null)
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.Session", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.HermesIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.TimelineEvent", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HermesDeck.Api.Domain.ToolCall", b =>
                {
                    b.HasOne("HermesDeck.Api.Domain.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
